### ISSUE TITLE
[question] Icon position not set when using an url

### ISSUE THREAD

**Issue by pardo-bsso** [souly1/ng-walkthrough#4]
Hi again, 
I'm using something like this:

```html
<walkthrough
            walkthrough-type="transparency"
            focus-element-id="element-id"
            icon="/img/tutorial/tutor_touch.png"
            main-caption="The Caption"                                                
</walkthrough>
```

and I had to make this change: https://github.com/CrearAyT/ng-walkthrough/commit/56fcad1d15d6c5d8750987de219cc58f22ddee8a because otherwise the icon is not positioned over the element. Is this really needed or am I doing something wrong? (that branch is rebased on top of your master)

Thanks.

**Comment by souly1** [comment]
you have the attributes 'icon-padding-left' and 'icon-padding-top' to quickly and simply place the icon to your liking, did you try them out?

**Comment by pardo-bsso** [comment]
Sorry, forgot that.
With a clean checkout of master and using:

```html
<walkthrough
            walkthrough-type="transparency"
            focus-element-id="navbar-favorites"
            icon="img/tutorial/tutor_touch.png"
            main-caption="some boring text..."
            icon-padding-left="0"
            icon-padding-top="440" >
</walkthrough>
```

The provided image appears but always horizontally centered at the top no matter what I put on the paddings.

For example, on the screenshot below the selector is for the heart icon on the navbar and with that padding (440) it should be positioned almost all the way to the bottom of the viewport while pointing at the heart and not there (at least that's what happens with our branch).

![ng_walkthrough_screenshot_1](https://cloud.githubusercontent.com/assets/940837/9518971/712bb692-4c91-11e5-88bf-dacf271d2183.jpg)

Thanks for looking at this.

**Comment by souly1** [comment]
Ok, updated the directive. Several things:
The old walkthrough did not support elements on the nav.bar, now it does but with special behaviour:
you will need to give a large left offset as the offset value jQuery retrieves for nav. bar is zero. in the Top offset i required a positive value so it won't be hidden behind the header (Icon won't be on element but rather close below).
In addition the nav.bar buttons functionality was fully available when the walkthrough was placed in ion-content, so in order to disable their functionality while walkthrough is displayed i added a new attribute to the directive called 'isBindClickEventToBody' which when set to true adds listeners to click event on body element when walkthrough is displayed and removes them when it is closed.
Hope this helps, If possible give an update.
Thanks
