### ISSUE TITLE
Walkthrough does not destroy on hardware back button while is-active = "true"

### ISSUE THREAD

**Issue by jeson114** [souly1/ng-walkthrough#51]
<walkthrough is-round=true
             walkthrough-type="transparency"
             focus-element-selector="#focus-Item"
             icon="new_hand"
             main-caption="Click to follow / Unfollow the Account"
             is-active="isHelp"
             icon-padding-left="20"
             icon-padding-top="20"
             use-button="true"
             has-glow="true"
             on-walkthrough-hide="disableHelp()">
</walkthrough>

i tried changing  $scope.isHelp on 

$ionicPlatform.registerBackButton(function(){
$scope.isHelp=false
},100);
 . while this does toggle $scope.isHelp to false  , it doesn't hide the walkthrough and also leads to the back button being unusable

**Comment by souly1** [comment]
Hi @jeson114 
Regarding the first issue, I see no reason this should not work, conceptually, so I'm guessing that cordova/ionic registration and call to events (aka `registerBackButton`) does not take into play the Angular lifecycle.
Try adding a `$scope.$digest();` after `$scope.isHelp = false;` and see what happens

About the second issue: I assume the back button not being usable is because the registration to the event overrides the default one. you should handle back as you see fit in this override. I'm guessing that if you'll look for it in stack overflow you'll find some posts about this issue.

Hope this helps, update how things work out.
Thanks
