### ISSUE TITLE
Show walkthrough once

### ISSUE THREAD

**Issue by RahulJyala** [souly1/ng-walkthrough#54]
I want to show walkthrough only  once in my application ? 
how can i achieve it ??
any idea?

Thanks

**Comment by souly1** [comment]
Hi Rahul, I'm unclear as to your question, you're able to show it multiple times (your previous question) but fail to show once?

**Comment by RahulJyala** [comment]
No , in my app where i'm applied walkthrough , i want to show walkthrough only one time in my application by one time means once the user uses the app he is able to show entire walkthrough only one time not again and again with refresh .

Thanks

**Comment by souly1** [comment]
Managing that it will not appear more than once depends on your app logic. The most popular way to do it is hold a flag in local memory if walkthrough done, check it each time and set it to true on walkthrough close.
Hope this brief explanation helps.
Thanks

**Comment by RahulJyala** [comment]
Yes, this is what I done so far , but clearing cache will reactive walkthrough So i guess I need to store is in database 

Thanks

**Comment by souly1** [comment]
Clearing browser cache will reactivate walkthrough with this kind of solution, but why would one clear cache? also, this might be a good think, giving ability to reset walkthrough's easily so that one can reload them.
And of course you can always use other persistent memory solutions such as a database or such...
Good luck!
